# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 640)
        self.frame_bg = QtWidgets.QFrame(Form)
        self.frame_bg.setGeometry(QtCore.QRect(10, 10, 1001, 591))
        self.frame_bg.setStyleSheet("background-color:rgb(57, 62, 70);\n"
"border-radius: 20px;")
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.label = QtWidgets.QLabel(self.frame_bg)
        self.label.setGeometry(QtCore.QRect(90, 30, 791, 61))
        font = QtGui.QFont()
        font.setFamily("Mitr")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 400 35pt \"Mitr\";\n"
"color:#fff")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bg_led = QtWidgets.QWidget(self.frame_bg)
        self.bg_led.setGeometry(QtCore.QRect(870, 10, 81, 81))
        self.bg_led.setStyleSheet("border-image: url(:/BG/bg_led.png);")
        self.bg_led.setObjectName("bg_led")
        self.widget_led = QtWidgets.QWidget(self.bg_led)
        self.widget_led.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.widget_led.setStyleSheet("\n"
" border-radius: 30px;\n"
"background-color: rgba(120, 120, 120, 0.874);\n"
"")
        self.widget_led.setObjectName("widget_led")
        self.label_2 = QtWidgets.QLabel(self.frame_bg)
        self.label_2.setGeometry(QtCore.QRect(840, 100, 151, 20))
        self.label_2.setStyleSheet("font: 900 12pt \"Mitr\";\n"
"color:white;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget_details = QtWidgets.QWidget(self.frame_bg)
        self.widget_details.setEnabled(True)
        self.widget_details.setGeometry(QtCore.QRect(20, 130, 961, 441))
        self.widget_details.setStyleSheet("background-color: rgb(109, 152, 134);")
        self.widget_details.setObjectName("widget_details")
        self.name_drug = QtWidgets.QLabel(self.widget_details)
        self.name_drug.setGeometry(QtCore.QRect(10, 10, 931, 31))
        self.name_drug.setStyleSheet("font: 400 20pt \"Mitr\";\n"
"color:#fff")
        self.name_drug.setAlignment(QtCore.Qt.AlignCenter)
        self.name_drug.setObjectName("name_drug")
        self.img_drug = QtWidgets.QLabel(self.widget_details)
        self.img_drug.setGeometry(QtCore.QRect(20, 60, 240, 360))
        self.img_drug.setStyleSheet("image: url(:/Drug/Drug/paracetamol.png);")
        self.img_drug.setText("")
        self.img_drug.setObjectName("img_drug")
        self.text_properties = QtWidgets.QTextBrowser(self.widget_details)
        self.text_properties.setGeometry(QtCore.QRect(340, 230, 601, 201))
        font = QtGui.QFont()
        font.setFamily("Mitr")
        font.setPointSize(14)
        self.text_properties.setFont(font)
        self.text_properties.setStyleSheet("background-color: #F2E7D5;\n"
"border-radius: 10px;")
        self.text_properties.setTabChangesFocus(False)
        self.text_properties.setUndoRedoEnabled(False)
        self.text_properties.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.text_properties.setReadOnly(True)
        self.text_properties.setOverwriteMode(False)
        self.text_properties.setAcceptRichText(True)
        self.text_properties.setOpenExternalLinks(False)
        self.text_properties.setObjectName("text_properties")
        self.head_text_properties = QtWidgets.QLabel(self.widget_details)
        self.head_text_properties.setGeometry(QtCore.QRect(600, 190, 101, 31))
        self.head_text_properties.setStyleSheet("font: 18pt \"Mitr\";\n"
"color:#fff;")
        self.head_text_properties.setObjectName("head_text_properties")
        self.label_use = QtWidgets.QLabel(self.widget_details)
        self.label_use.setGeometry(QtCore.QRect(340, 120, 601, 41))
        self.label_use.setStyleSheet("font: 18pt \"Mitr\";\n"
"color:#000;\n"
"background-color: #F2E7D5;\n"
"border-radius: 10px;")
        self.label_use.setObjectName("label_use")
        self.head_label_use = QtWidgets.QLabel(self.widget_details)
        self.head_label_use.setGeometry(QtCore.QRect(610, 80, 81, 31))
        self.head_label_use.setStyleSheet("font: 18pt \"Mitr\";\n"
"color:#fff")
        self.head_label_use.setObjectName("head_label_use")
        self.label_time = QtWidgets.QLabel(self.frame_bg)
        self.label_time.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_time.setStyleSheet("font: 18pt \"Mitr\";\n"
"color:#fff")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_12 = QtWidgets.QLabel(self.frame_bg)
        self.label_12.setGeometry(QtCore.QRect(70, 18, 71, 21))
        self.label_12.setStyleSheet("font: 400 18pt \"Mitr\";\n"
"color:#fff;\n"
"background-color: rgba(242, 231, 213, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(830, 610, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 610, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "โครงงานตู้อ่านฉลากยาอัตโนมัติ"))
        self.label_2.setText(_translate("Form", "RFID STATUS"))
        self.name_drug.setText(_translate("Form", "ยาพาราเซตามอล"))
        self.text_properties.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mitr\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#000000;\">ใช้รักษาอาการปวดศีรษะปวดจากข้อเสื่อมปวดกล้ามเนื้อและใช้เป็นยาลดไข้ </span></p></body></html>"))
        self.head_text_properties.setText(_translate("Form", "สรรพคุณ"))
        self.label_use.setText(_translate("Form", "กินยาห่างกันอย่างน้อย 4 ชั่วโมง"))
        self.head_label_use.setText(_translate("Form", "วิธีใช้ยา"))
        self.label_time.setText(_translate("Form", "23:00"))
        self.label_12.setText(_translate("Form", "น."))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton2"))
import MyImg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
