# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 640)
        self.frame_bg = QtWidgets.QFrame(Form)
        self.frame_bg.setGeometry(QtCore.QRect(10, 10, 1001, 591))
        self.frame_bg.setStyleSheet("background-color:rgb(57, 62, 70);\n"
"border-radius: 20px;")
        self.frame_bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg.setObjectName("frame_bg")
        self.label = QtWidgets.QLabel(self.frame_bg)
        self.label.setGeometry(QtCore.QRect(90, 30, 791, 61))
        font = QtGui.QFont()
        font.setFamily("Mitr")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 400 35pt \"Mitr\";\n"
"color:#fff")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bg_led = QtWidgets.QWidget(self.frame_bg)
        self.bg_led.setGeometry(QtCore.QRect(870, 10, 81, 81))
        self.bg_led.setStyleSheet("border-image: url(:/BG/bg_led.png);")
        self.bg_led.setObjectName("bg_led")
        self.widget_led = QtWidgets.QWidget(self.bg_led)
        self.widget_led.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.widget_led.setStyleSheet("\n"
" border-radius: 30px;\n"
"background-color: rgba(120, 120, 120, 0.874);\n"
"")
        self.widget_led.setObjectName("widget_led")
        self.label_2 = QtWidgets.QLabel(self.frame_bg)
        self.label_2.setGeometry(QtCore.QRect(840, 100, 151, 20))
        self.label_2.setStyleSheet("font: 900 12pt \"Mitr\";\n"
"color:white;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget_main = QtWidgets.QWidget(self.frame_bg)
        self.widget_main.setEnabled(True)
        self.widget_main.setGeometry(QtCore.QRect(20, 130, 961, 441))
        self.widget_main.setStyleSheet("background-color: rgb(109, 152, 134);")
        self.widget_main.setObjectName("widget_main")
        self.logo_school = QtWidgets.QLabel(self.widget_main)
        self.logo_school.setGeometry(QtCore.QRect(90, 10, 321, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_school.sizePolicy().hasHeightForWidth())
        self.logo_school.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.logo_school.setFont(font)
        self.logo_school.setStyleSheet("border-image: url(:/img/logo_school.png);")
        self.logo_school.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_school.setText("")
        self.logo_school.setWordWrap(False)
        self.logo_school.setObjectName("logo_school")
        self.layoutWidget = QtWidgets.QWidget(self.widget_main)
        self.layoutWidget.setGeometry(QtCore.QRect(560, 60, 321, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mitr")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:rgba(242, 231, 213, 0.800);\n"
"border-radius:15px;\n"
"font: 400 16pt \"Mitr\";\n"
"box-shadow: 2px 2px 8px 4px rgba(0, 0, 0, 0.25);\n"
"\n"
"")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lcd_tem_box1 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcd_tem_box1.setGeometry(QtCore.QRect(140, 40, 101, 41))
        self.lcd_tem_box1.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lcd_tem_box1.setTabletTracking(False)
        self.lcd_tem_box1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcd_tem_box1.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lcd_tem_box1.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_tem_box1.setSmallDecimalPoint(False)
        self.lcd_tem_box1.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_tem_box1.setProperty("value", 0.0)
        self.lcd_tem_box1.setObjectName("lcd_tem_box1")
        self.lcd_damp_box1 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcd_damp_box1.setGeometry(QtCore.QRect(140, 90, 101, 41))
        self.lcd_damp_box1.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lcd_damp_box1.setTabletTracking(False)
        self.lcd_damp_box1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcd_damp_box1.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lcd_damp_box1.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_damp_box1.setSmallDecimalPoint(False)
        self.lcd_damp_box1.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_damp_box1.setProperty("value", 0.0)
        self.lcd_damp_box1.setObjectName("lcd_damp_box1")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(240, 40, 51, 41))
        self.label_3.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 90, 51, 41))
        self.label_4.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 121, 41))
        self.label_5.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 121, 41))
        self.label_6.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mitr")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color:rgba(242, 231, 213, 0.800);\n"
"border-radius:15px;\n"
"font: 400 16pt \"Mitr\";\n"
"box-shadow: 2px 2px 8px 4px rgba(0, 0, 0, 0.25);\n"
"\n"
"")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcd_tem_box2 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcd_tem_box2.setGeometry(QtCore.QRect(140, 40, 101, 41))
        self.lcd_tem_box2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lcd_tem_box2.setTabletTracking(False)
        self.lcd_tem_box2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcd_tem_box2.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lcd_tem_box2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_tem_box2.setSmallDecimalPoint(False)
        self.lcd_tem_box2.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_tem_box2.setProperty("value", 0.0)
        self.lcd_tem_box2.setObjectName("lcd_tem_box2")
        self.lcd_damp_box2 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcd_damp_box2.setGeometry(QtCore.QRect(140, 90, 101, 41))
        self.lcd_damp_box2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lcd_damp_box2.setTabletTracking(False)
        self.lcd_damp_box2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcd_damp_box2.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lcd_damp_box2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_damp_box2.setSmallDecimalPoint(False)
        self.lcd_damp_box2.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_damp_box2.setProperty("value", 0.0)
        self.lcd_damp_box2.setObjectName("lcd_damp_box2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(240, 40, 51, 41))
        self.label_7.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(240, 90, 51, 41))
        self.label_8.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 121, 41))
        self.label_9.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 121, 41))
        self.label_10.setStyleSheet(" background-color: rgba(242, 231, 213, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label_time = QtWidgets.QLabel(self.frame_bg)
        self.label_time.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_time.setStyleSheet("font: 18pt \"Mitr\";\n"
"color:#fff")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_12 = QtWidgets.QLabel(self.frame_bg)
        self.label_12.setGeometry(QtCore.QRect(70, 18, 71, 21))
        self.label_12.setStyleSheet("font: 400 18pt \"Mitr\";\n"
"color:#fff;\n"
"background-color: rgba(242, 231, 213, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(830, 610, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 610, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.widget_main.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "โครงงานตู้อ่านฉลากยาอัตโนมัติ"))
        self.label_2.setText(_translate("Form", "RFID STATUS"))
        self.groupBox.setTitle(_translate("Form", "ตู้ยา"))
        self.label_3.setText(_translate("Form", "°C"))
        self.label_4.setText(_translate("Form", "%"))
        self.label_5.setText(_translate("Form", "ความชื้น"))
        self.label_6.setText(_translate("Form", "อุณหภูมิ"))
        self.groupBox_2.setTitle(_translate("Form", "ตู้ควบคุม"))
        self.label_7.setText(_translate("Form", "°C"))
        self.label_8.setText(_translate("Form", "%"))
        self.label_9.setText(_translate("Form", "ความชื้น"))
        self.label_10.setText(_translate("Form", "อุณหภูมิ"))
        self.label_time.setText(_translate("Form", "23:00"))
        self.label_12.setText(_translate("Form", "น."))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton2"))
import MyImg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
